apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ikaczcvhy-nodejs 
  janus-idp.io/tekton: ikaczcvhy-nodejs
  backstage.io/kubernetes-id: ikaczcvhy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ikaczcvhy-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  